### ISSUE TITLE
Return instructions present in region after inlining

### ISSUE THREAD

**Issue by vaibhavbsharma** [sohah/VeritestingTransformations#24]
We still have a few return statements left behind in the AST of a region that contained higher-order regions after substitution. This happens when running the [replace_5 benchmark](https://github.com/sohah/veritestingBenchmarks/tree/master/TSE-2017/repalce_5). Here's a log file from a run on my lab machine: [replace_5.log.tar.gz](https://github.com/sohah/VeritestingTransformations/files/2470681/replace_5.log.tar.gz)

You can see this in the log file (after gunzipping it). If you look at the region `replace.omatch([C[CI)Z#10` in the region summary printed in the "AFTER SUBSTITUTION TRANSFORMATION" part, it contains several `return 1` statements and also a `return @w-1$23` statement. I think return statements shouldn't be introduced in the region after substitution. But please correct me if I am wrong. Please let me know if you need more information regarding this bug.

**Comment by sohah** [comment]
I fixed that in [this](https://github.com/sohah/VeritestingTransformations/commit/cccc1d0144381a16e2fe8200ac389149e675e819) commit. Can you please check that there are no return statements and close the bug if there are no more. 

Thanks!

**Comment by vaibhavbsharma** [comment]
I re-ran replace_5 with all the commit you referred to just above. I am still seeing regions with return instructions in the summary in the "After Substitution Transformation" section in the logged output. Here's the log file from my run: [replace.log.zip](https://github.com/sohah/VeritestingTransformations/files/2471368/replace.log.zip)

**Comment by sohah** [comment]
Vaibhav, I think those from the early return, currently this is not supported, they should disappear when we have early returns in place.

**Comment by vaibhavbsharma** [comment]
I am having trouble figuring out if these returns are showing up because of unsupported early returns. I propose keeping this issue open until we have early returns working with replace_5. As of today, I can see region instantiation failing because of return instructions showing up in unexpected transformations. Here's my log file: 
[replace.log.zip](https://github.com/sohah/VeritestingTransformations/files/2476713/replace.log.zip)

**Comment by vaibhavbsharma** [comment]
Closing this issue since the returns that kept showing up were truly because of early return regions.
